### ISSUE TITLE
picture

### ISSUE THREAD

**Issue by martymoose** [erikkallen/Marlin_tronxy#1]
do you have a picture of the board
love to run this firmware
can i buy board of ebay?
cheers great work

**Comment by erikkallen** [comment]
Hey marty,

I bought my board from aliexpress https://nl.aliexpress.com/store/product/3d-printer-control-board-melzi-mainboard-zonestar/1951499_32515393148.html?spm=2114.12010608.0.0.809dRP

if you follow the link you can see the picture as well the board is called melzi you should be able to find it on ebay.

-erik
